name: my first gitactionion workflow
on:
  push:
    branches: ["main"]  
    # pull:
    #   branches: ["main"]  
    # push_request:
    #   branches: ["main"]
jobs:
  my-first-gitactionion-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "my first gitactionion workflow is working!"
      - name: Setup Python
        uses: actions/setup-python@v5   
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt 
      - name: Run Tests
        run: |
          pytest -v --junitxml=test-results.xml || true   
      - name: Say Hello Again
        run: echo "my first gitactionion workflow is working again!"
